/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.librarymanagementsystem;
import javax.swing.JOptionPane;
/**
 *
 * @author ANTRIKSH
 */
public class AdminLoginLibrary extends javax.swing.JFrame {

    /**
     * Creates new form AdminLoginLibrary
     */
    public AdminLoginLibrary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginSubmitButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        HomeFromLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        SignupFromLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AdminUsername = new javax.swing.JTextField();
        AdminPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AdminLoginAccessCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginSubmitButton.setBackground(new java.awt.Color(0, 0, 0));
        LoginSubmitButton.setForeground(new java.awt.Color(204, 255, 255));
        LoginSubmitButton.setText("Submit");
        LoginSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginSubmitButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("LIBRARY MANAGEMENT SYSTEM(ADMIN LOGIN)");

        HomeFromLogin.setBackground(new java.awt.Color(0, 0, 0));
        HomeFromLogin.setForeground(new java.awt.Color(204, 255, 255));
        HomeFromLogin.setText("Home");
        HomeFromLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeFromLoginActionPerformed(evt);
            }
        });

        jLabel4.setText("Not signed up?");

        SignupFromLogin.setBackground(new java.awt.Color(0, 0, 0));
        SignupFromLogin.setForeground(new java.awt.Color(204, 255, 255));
        SignupFromLogin.setText("Signup");
        SignupFromLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupFromLoginActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("Username: ");

        jLabel2.setBackground(new java.awt.Color(204, 153, 0));
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("Password:");

        AdminUsername.setBackground(new java.awt.Color(255, 204, 204));
        AdminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminUsernameActionPerformed(evt);
            }
        });

        AdminPassword.setBackground(new java.awt.Color(255, 204, 204));
        AdminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPasswordActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("Admin Access Code: ");

        AdminLoginAccessCode.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HomeFromLogin))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoginSubmitButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(173, 173, 173)))
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SignupFromLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AdminPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(AdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminLoginAccessCode))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HomeFromLogin)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AdminLoginAccessCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginSubmitButton)
                    .addComponent(jLabel4)
                    .addComponent(SignupFromLogin))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginSubmitButtonActionPerformed
        String clientLoginUsername = AdminUsername.getText();
        String clientLoginPassword = AdminPassword.getText();
        String adminAccessCode = AdminLoginAccessCode.getText();

        System.out.println(clientLoginUsername);
        System.out.println(clientLoginPassword);
        Database db = new Database();
        boolean isLoggedIn = db.checkAdminLogin(clientLoginUsername, clientLoginPassword,adminAccessCode);
        if(isLoggedIn){
            dispose();
            AdminDashboard ad = new AdminDashboard();
            ad.setVisible(true);
            
        }
        else{
            System.out.println("Username: " + clientLoginUsername);
            System.out.println("Password: " + clientLoginPassword);
            System.out.println("Please check the provided credentials again!");
            dispose();
            LoginLibrary ll = new LoginLibrary();
            ll.setVisible(true);
            JOptionPane.showMessageDialog(this, "Please check the provided credentials again!", "Login Failed", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_LoginSubmitButtonActionPerformed

    private void HomeFromLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeFromLoginActionPerformed
        // TODO add your handling code here:
        dispose();
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_HomeFromLoginActionPerformed

    private void SignupFromLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupFromLoginActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminSignupLibrary asl = new AdminSignupLibrary();
        asl.setVisible(true);
    }//GEN-LAST:event_SignupFromLoginActionPerformed

    private void AdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminPasswordActionPerformed

    private void AdminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLoginLibrary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminLoginAccessCode;
    private javax.swing.JTextField AdminPassword;
    private javax.swing.JTextField AdminUsername;
    private javax.swing.JButton HomeFromLogin;
    private javax.swing.JButton LoginSubmitButton;
    private javax.swing.JButton SignupFromLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
