/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.librarymanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author ANTRIKSH
 */
public class LoginLibrary extends javax.swing.JFrame {

    /**
     * Creates new form LoginLibrary
     */
    public LoginLibrary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clientUsername = new javax.swing.JTextField();
        clientPassword = new javax.swing.JTextField();
        LoginSubmitButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        HomeFromLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        SignupFromLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("Username: ");

        jLabel2.setBackground(new java.awt.Color(204, 153, 0));
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setText("Password:");

        clientUsername.setBackground(new java.awt.Color(255, 204, 204));
        clientUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientUsernameActionPerformed(evt);
            }
        });

        clientPassword.setBackground(new java.awt.Color(255, 204, 204));
        clientPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientPasswordActionPerformed(evt);
            }
        });

        LoginSubmitButton.setBackground(new java.awt.Color(0, 0, 0));
        LoginSubmitButton.setForeground(new java.awt.Color(204, 255, 255));
        LoginSubmitButton.setText("Submit");
        LoginSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginSubmitButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("LIBRARY MANAGEMENT SYSTEM(USER AND STAFF LOGIN)");

        HomeFromLogin.setBackground(new java.awt.Color(0, 0, 0));
        HomeFromLogin.setForeground(new java.awt.Color(204, 255, 255));
        HomeFromLogin.setText("Home");
        HomeFromLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeFromLoginActionPerformed(evt);
            }
        });

        jLabel4.setText("Not signed up?");

        SignupFromLogin.setBackground(new java.awt.Color(0, 0, 0));
        SignupFromLogin.setForeground(new java.awt.Color(204, 255, 255));
        SignupFromLogin.setText("Signup");
        SignupFromLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupFromLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoginSubmitButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(28, 28, 28)
                            .addComponent(clientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(clientPassword))))
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignupFromLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HomeFromLogin))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HomeFromLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginSubmitButton)
                    .addComponent(jLabel4)
                    .addComponent(SignupFromLogin))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginSubmitButtonActionPerformed
        String clientLoginUsername = clientUsername.getText();
        String clientLoginPassword = clientPassword.getText();
        
        System.out.println(clientLoginUsername);
        System.out.println(clientLoginPassword);
        Database db = new Database();
        boolean isLoggedIn = db.checkLogin(clientLoginUsername, clientLoginPassword);
        if(isLoggedIn){
            dispose();
            DashBoard dashb = new DashBoard();
            dashb.setVisible(true);
        }
        else{
            System.out.println("Username: " + clientLoginUsername);
            System.out.println("Password: " + clientLoginPassword);
            System.out.println("Please check the provided credentials again!");
            dispose();
            LoginLibrary ll = new LoginLibrary();
            ll.setVisible(true);
            JOptionPane.showMessageDialog(this, "Please check the provided credentials again!", "Login Failed", JOptionPane.WARNING_MESSAGE);

        }
        
        
    }//GEN-LAST:event_LoginSubmitButtonActionPerformed

    private void clientPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientPasswordActionPerformed

    private void HomeFromLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeFromLoginActionPerformed
        // TODO add your handling code here:
        dispose();
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_HomeFromLoginActionPerformed

    private void SignupFromLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupFromLoginActionPerformed
        // TODO add your handling code here:
        dispose();
        SignupLibrary sl = new SignupLibrary();
        sl.setVisible(true);
    }//GEN-LAST:event_SignupFromLoginActionPerformed

    private void clientUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginLibrary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeFromLogin;
    private javax.swing.JButton LoginSubmitButton;
    private javax.swing.JButton SignupFromLogin;
    private javax.swing.JTextField clientPassword;
    private javax.swing.JTextField clientUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
